Update files to match output generated by minimal template command
MarkBind/init-minimal-netlify pull request #1
Opened 2023-01-20 08:34 UTC by yucheng11122017

**What is the purpose of this pull request?**
Update files to latest files generated by markbind init as mentioned in [#1810](https://github.com/MarkBind/markbind/issues/1810)

**Overview of changes**
Files match the files generated by markbind init

**Anything you'd like to highlight/discuss:**
nil

**Testing instructions:**

**Proposed commit message: (wrap lines at 72 characters)**

`
Update repo to match output of current version of init command --template 
minimal
`
Checklist:

- [ ] Updated the documentation for feature additions and enhancements
- [ ] Added tests for bug fixes or features
- [X] Linked all related issues
- [X] No unrelated changes

2023-01-20 12:38 UTC, tlylt requested changes
Hi @yucheng11122017, thanks for the work!

Could you help me double check all the files included again, and remove unnecessary ones?
I am seeing files like:
- .idea IDE files
- log files

being committed.

2023-01-20 14:11 UTC, yucheng11122017 commented
@tlylt Apologies, I must have missed it. I've removed them

2023-01-21 01:31 UTC, tlylt commented
Thanks @yucheng11122017, LGTM.
P.S. I am waiting for write access to this repo before I can merge and also follow up with the Netlify issues.

2023-01-26 06:03 UTC, tlylt approved these changes

2023-01-26 06:04 UTC, merged